-- CivicLens AI — PostgreSQL schema
-- Requires: CREATE EXTENSION IF NOT EXISTS "pgcrypto"; (for gen_random_uuid)

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────
-- Users (created via Google Sign-In, progressively profiled)
-- ─────────────────────────────────────────────
CREATE TABLE users (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  google_id         TEXT UNIQUE NOT NULL,
  email             TEXT UNIQUE NOT NULL,
  name              TEXT NOT NULL,
  username          TEXT UNIQUE,              -- filled during progressive profiling
  occupation        TEXT,
  city              TEXT,
  district          TEXT,
  photo_url         TEXT,
  role              TEXT NOT NULL DEFAULT 'citizen' CHECK (role IN ('citizen', 'admin', 'moderator')),
  profile_completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────
-- Issue categories (predefined, extensible)
-- ─────────────────────────────────────────────
CREATE TABLE categories (
  id      SERIAL PRIMARY KEY,
  slug    TEXT UNIQUE NOT NULL,       -- e.g. 'pothole', 'garbage', 'streetlight'
  label   TEXT NOT NULL,
  parent_department TEXT              -- e.g. 'Roads', 'Sanitation', 'Electrical' — used for duplicate-check category mismatch rule
);

-- ─────────────────────────────────────────────
-- Issues (citizen reports)
-- ─────────────────────────────────────────────
CREATE TABLE issues (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category_id        INTEGER NOT NULL REFERENCES categories(id),
  title              TEXT NOT NULL,
  description        TEXT NOT NULL,
  solution_idea       TEXT,                    -- optional "how can this be solved?"
  status             TEXT NOT NULL DEFAULT 'pending_review'
                       CHECK (status IN ('pending_review', 'approved', 'rejected', 'potential_duplicate', 'resolved')),
  lat                DOUBLE PRECISION NOT NULL,
  lng                DOUBLE PRECISION NOT NULL,
  address_hint       TEXT,
  ai_summary         TEXT,                     -- generated by AI service
  ai_suggestion      TEXT,                     -- generated by AI service
  reviewed_by        UUID REFERENCES users(id),
  reviewed_at        TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at        TIMESTAMPTZ
);

CREATE INDEX idx_issues_status ON issues(status);
CREATE INDEX idx_issues_category ON issues(category_id);
CREATE INDEX idx_issues_location ON issues(lat, lng);
CREATE INDEX idx_issues_created_at ON issues(created_at);

-- ─────────────────────────────────────────────
-- Images attached to an issue
-- ─────────────────────────────────────────────
CREATE TABLE issue_images (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_id            UUID NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  url                 TEXT NOT NULL,
  exif_lat            DOUBLE PRECISION,
  exif_lng            DOUBLE PRECISION,
  dominant_color      TEXT,                     -- e.g. '#5b5b5b' — cheap signal for image-similarity comparisons
  is_ai_generated     BOOLEAN,                   -- result of authenticity check (C2PA / SynthID signals)
  authenticity_checked_at TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_issue_images_issue ON issue_images(issue_id);

-- ─────────────────────────────────────────────
-- Duplicate detection flags (human-in-the-loop queue)
-- ─────────────────────────────────────────────
CREATE TABLE duplicate_flags (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  issue_id          UUID NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  matched_issue_id  UUID NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  similarity_score  NUMERIC(4,3) NOT NULL,        -- 0.000–1.000
  spatial_match     BOOLEAN NOT NULL,
  temporal_match    BOOLEAN NOT NULL,
  semantic_match    BOOLEAN NOT NULL,
  status            TEXT NOT NULL DEFAULT 'pending_review'
                      CHECK (status IN ('pending_review', 'confirmed_merge', 'rejected_as_duplicate', 'marked_related')),
  reviewed_by       UUID REFERENCES users(id),
  reviewed_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_duplicate_flags_status ON duplicate_flags(status);

-- ─────────────────────────────────────────────
-- Admin action audit log
-- ─────────────────────────────────────────────
CREATE TABLE admin_actions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id    UUID NOT NULL REFERENCES users(id),
  issue_id    UUID REFERENCES issues(id) ON DELETE CASCADE,
  action      TEXT NOT NULL,     -- 'approve' | 'reject' | 'merge' | 'mark_related' | 'resolve'
  notes       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────
-- Cached local news headlines (trusted-source feed)
-- ─────────────────────────────────────────────
CREATE TABLE news_cache (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title          TEXT NOT NULL,
  url            TEXT NOT NULL,
  source         TEXT NOT NULL,
  image_url      TEXT,
  locale         TEXT NOT NULL,     -- city/region keyword used for the query
  category       TEXT NOT NULL DEFAULT 'local', -- 'local' | 'city' | 'national'
  published_at   TIMESTAMPTZ,
  fetched_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_news_locale_category ON news_cache(locale, category);
